### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by ghost** [micimize/graphql-to-dart#1]
I assume this is meant to be used with graphql-flutter package  ? 
It would be awesome to see an example hooked up with flutter if you have time.

**Comment by micimize** [comment]
apologies, much to my chagrin I have apparently not been getting notifications from any of my projects for quite some time.

You are quite right that this is meant to be used with graphql-flutter! It doesn't have any specific integration though. It's also in dire need of an update (#2), which hopefully I'll be able to get to soon

**Comment by micimize** [comment]
closed by #8

**Comment by micimize** [comment]
<img width="395" alt="Screen Shot 2019-03-13 at 17 45 52" src="https://user-images.githubusercontent.com/8343799/54319826-e5032b80-45b8-11e9-962a-8a38192236d3.png">
