### ISSUE TITLE
Non nullable fields in graphql vs required fields in models

### ISSUE THREAD

**Issue by PeterZainzinger** [micimize/graphql-to-dart#15]
Hi,

we again run into problems with the required fields. Lets consider the following minimal example:

```graphql
type Query {
  getBooks(): [Book!]
}

type Book {
 name: String!
 category : Category!
}

type Category{
  name: String!
  books: [Book!]!
}
```

If i want to query now for `books -> category -> ... -> books` and some point the category or the books array has to be null which breaks the parsing.

In my opinion the root cause if the problem is that two different concepts are mixed up

* non nullable fields in graphql
* required fields in the data model

This also leads to problems if non nullable fields are not selected, the parsing fails which should also not be the case. As far as I understand it's the idea of graphql to select only the fields you need, which does not mean that the fields you are not selecting can't be not nullable. 

A possible solution would be to make the `required: true, disallowNullValue: true` configurable or to remove it completely. I would go the for the later.

**Comment by micimize** [comment]
This shouldn't be an issue - are you using the models generated from the query string when deserializing? It should be generating a [different model for each subquery](https://github.com/micimize/graphql-to-dart/blob/master/example/lib/starwars_graphql_serializers.dart#L2379).

If I remember correctly, it ends up looking like `BookCategoryQueryBook`, `BookCategoryQuery_Book`, ... for each nesting, unless they're differently named fragments

**Comment by PeterZainzinger** [comment]
> This shouldn't be an issue - are you using the models generated from the query string when deserializing?

Yes.

> If I remember correctly, it ends up looking like BookCategoryQueryBook, BookCategoryQuery_Book, ... for each nesting, unless they're differently named fragments

That's not the case. Even if it would be it would solve the issue. The problem is the recursive nature of the graphql model. It's not possible nor feasable to generate types for every possible subquery because a query like this can in theory be nested as many times as wanted.

This is a valid query.

```graphql
query books1 {
  getBooks {
    name
    category {
      name
      books {
        name
        category {
          name
          # here I'm not interested in any more books of the category, 
          # so I don't select it, so it's null which breaks the parsing
        }
      }
    }
  }
}

```
Here is the relevant output.

```dart
@JsonSerializable()
class Book implements ToJson {

  String __typename;

  
    @JsonKey(required: true, disallowNullValue: true,)
    String name;
    @JsonKey(required: true, disallowNullValue: true,)
    Category category;


  Book({
    @required this.name,
    @required this.category,
    
  });

  /// Construct an empty `Book`
  Book.empty();


  /// Adds all fields from [other] to this `Book`.
  /// 
  /// If a field from [other] is already in this `Book`,
  /// its value is overwritten, unless  `overwrite: true` is specified
  void addAll(covariant Book other, { bool overwrite = true, }) {
     assert(other != null, "Cannot add all from null into $this");
     if (overwrite != null && overwrite){
        
        name = other.name ?? name;
        category = other.category ?? category;
     } else {
        
        name ??= other.name;
        category ??= other.category;
     }
  }

  /// Creates a copy of this `Book` but with the given fields replaced with the new values.
  Book copyWith({        
            String name,        
            Category category,
    }){
        return Book(
            
            name: name ?? this.name,
            category: category ?? this.category,
        );
  }

  /// Creates a copy of this `Book`
  Book copy() => copyWith();


  factory Book.fromJson(Map<String, dynamic> json) => 
    deserializeFromJson(json);

  Map<String, dynamic> toJson() => serializeToJson(this);

  static Book deserializeFromJson(Map<String, dynamic> json){
    Book instance = _$BookFromJson(json);
    // for handling inline fragment logic 
    instance.__typename = json['__typename'] as String;

    return instance;
  }


  static Map<String, dynamic> serializeToJson(Book instance){
    Map<String, dynamic> json = _$BookToJson(instance);

    return json;
  }

}




/// 
@JsonSerializable()
class Category implements ToJson {

  String __typename;

  
    @JsonKey(required: true, disallowNullValue: true,)
    String name;
    @JsonKey(required: true, disallowNullValue: true,)
    List<Book> books;


  Category({
    @required this.name,
    @required this.books,
    
  });

  /// Construct an empty `Category`
  Category.empty();


  /// Adds all fields from [other] to this `Category`.
  /// 
  /// If a field from [other] is already in this `Category`,
  /// its value is overwritten, unless  `overwrite: true` is specified
  void addAll(covariant Category other, { bool overwrite = true, }) {
     assert(other != null, "Cannot add all from null into $this");
     if (overwrite != null && overwrite){
        
        name = other.name ?? name;
        books = other.books ?? books;
     } else {
        
        name ??= other.name;
        books ??= other.books;
     }
  }

  /// Creates a copy of this `Category` but with the given fields replaced with the new values.
  Category copyWith({        
            String name,        
            List<Book> books,
    }){
        return Category(
            
            name: name ?? this.name,
            books: books ?? this.books,
        );
  }

  /// Creates a copy of this `Category`
  Category copy() => copyWith();


  factory Category.fromJson(Map<String, dynamic> json) => 
    deserializeFromJson(json);

  Map<String, dynamic> toJson() => serializeToJson(this);

  static Category deserializeFromJson(Map<String, dynamic> json){
    Category instance = _$CategoryFromJson(json);
    // for handling inline fragment logic 
    instance.__typename = json['__typename'] as String;

    return instance;
  }


  static Map<String, dynamic> serializeToJson(Category instance){
    Map<String, dynamic> json = _$CategoryToJson(instance);

    return json;
  }

}
```

**Comment by micimize** [comment]
These look like the base type models. If your query is in a document referenced in the `codegen.yml`, like
```yml
documents:
  - "./lib/gql/RecursiveGetBooks.gql"
```
And assuming it's renamed to `booksOne`, then it should be generating models like `BooksOneGetBooks`, `BooksOneCategory`, `BooksOne_Category` as well. This (crudely) solves the recursion issue by generating a new model for each nested level.

**Comment by PeterZainzinger** [comment]
Using the documents fields is not a solution because I have very little control of which queries are needed. 

In my point of view this would make the whole graphql thing pointless if you would have to know which queries are needed for the client to generate the correct types. 

If you would accept a pull request which adds a configuration option to disable the required fields/non null fields altogether i would go for that, otherwise we probably have to fork and create a new package.

**Comment by micimize** [comment]
@PeterZainzinger a PR would def be welcome 👍
