### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ryankauk** [micimize/graphql-to-dart#20]
Hey, I updated flutter and in turn updated this package but it couldn't be installed.

```

> @graphql-codegen/near-operation-file-preset@1.9.3-beta3 prepack 
> bob-update-version

sh: bob-update-version: command not found
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
```

**Comment by micimize** [comment]
hmm, sorry about that - missed it because `yarn` doesn't call `prepack`
Try `npm install graphql-to-dart@1.1.4-beta`
