### ISSUE TITLE
Problem with aliases (on master)

### ISSUE THREAD

**Issue by EugenePisotsky** [micimize/graphql-to-dart#22]
Hi, 

There's a problem with aliases. Query like this:

```graphql
    route: geoRoute(locations: $locations) {
        ...RouteFragment
    }

    targetRoute: geoRoute(locations: $locationsAll) {
        ...RouteFragment
    }
```

... is generated to this code:

```dart
SimulatorRoutesQuery({
          @required SimulatorRouteFragmentRoute route,
          @required SimulatorRouteFragmentTargetRoute targetRoute,
      
  }): super(
      geoRoute: route,
      geoRoute: targetRoute,
  )
```

(2 geoRoute passed to super)

**Comment by micimize** [comment]
oh heck, you're right. I guess we need to recognize a field accessed multiple times and add additional properties to the fields object for each beyond the 1st

**Comment by EugenePisotsky** [comment]
also, probably not the best way, but as a workaround I was thinking about using map for aliased fields in the root `Query` class, something like:

```dart
Map<String, dynamic> aliasedFields = Map();
```

and if `schemaFieldName` not equals to `name`, mixin can set / get it from the `aliasedFields` map

**Comment by micimize** [comment]
`1.1.5-beta` fixes this specific issue, but there are still some serious problems in #24
