### ISSUE TITLE
Inline fragments are broken, unions won't be deserialized

### ISSUE THREAD

**Issue by micimize** [micimize/graphql-to-dart#24]
- [x] Unions need to implement a discriminated union deserializer. Here's what looks like a relevant block in [json_serializable](https://github.com/dart-lang/json_serializable/blob/6d5948508b65d8bec873b3fc213c17c884546156/json_serializable/test/src/json_converter_test_input.dart#L74-L85).
- [x] (Harder) inline fragments aren't generated properly - 
```graphql
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    # without typename we can't really tell which fragments to parse
    __typename
    name
    ... on Droid {
      primaryFunction
    }
    ... on Human {
      appearsIn
      ...info
      ...relationships
    }
  }
}
```
generates the `HeroForEpisode{ Human, Droid }InlineFragment` models,
but the top level model is just
```dart
class HeroForEpisodeHero extends Character with HelloMixin {
  static final String typeName = "Character";

  @JsonKey(name: r'name', required: true, disallowNullValue: true)
  String get name => fields.name;
  set name(String name) => fields.name = name;
  HeroForEpisodeHero({
    @required String name,
  }) : super(
          name: name,
        );
//...
```

**Comment by micimize** [comment]
No, we can probably put `HeroForEpisodeDroidInlineFragment onDroid` fields on selection sets and let them handle themselves. I must have been doing this before 1.0

**Comment by micimize** [comment]
Ok, I believe I've solved this on `1.2.0-beta`. Also added some config options:
```ts
  /**
   * Field to base union / inline fragment resolution on. Field will be `@protected`
   * @default '__typename'
   *
   * Can be set to `false` to disable automatic addition of meta fields
   */
  typenameField?: false | string;

  /**
   * { prefix, suffix } to wrap inline fragment type names with
   *
   * @example '{ prefix: "on", suffix: "" } => SomeTypeInlineFragment onSomeType'
   * @default '{ prefix: "", suffix: "InlineFragment" }'
   */
  inlineFragmentFieldNames?: { prefix?: string; suffix?: string };
```

**Comment by micimize** [comment]
@ryankauk let me know if you encounter any more issues

**Comment by ryankauk** [comment]
@micimize alright thanks!

**Comment by ryankauk** [comment]
@micimize fragments don't seem to work in my environment. Fragment doesn't exist when used by document outside of my _fragment.gql even though i split the globs. my best guess is that @graphql-codegen/cli probably changed the way they load documents globs, however you can easily just for loop over all the fragments before the handlebars gets ran.

I can refactor but can you explain what scenario the 'hackFragmentFields "ensure_unique"' prevents so I refactor properly?
