### ISSUE TITLE
Include documents in output

### ISSUE THREAD

**Issue by EugenePisotsky** [micimize/graphql-to-dart#9]
Hello,

It works nice already, but would be better if output will also contain document, so there's no need to load file.

```
const HeroForEpisodeDoc = """query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    __typename
    name
    ... on Droid {
      primaryFunction
    }
    ... on Human {
      height
      homePlanet
    }
  }
}""";
```

**Comment by micimize** [comment]
This might be doable with a [graphql-code-generator plugin](https://graphql-code-generator.com/docs/custom-codegen/) or something - it seems difficult and error prone to me though. I have [some utilities](https://github.com/micimize/graphql-to-dart/blob/master/example/lib/utils.dart) for making file loading easier - what I'd really like to do is output the input queries as the `toString` on their models, or something like that.

**Comment by micimize** [comment]
You can now import/export `gql_code_gen` generated asts with the [beta](https://github.com/micimize/graphql-to-dart#beta)

Eventually the `gql_code_gen` will have it's own [type generation](https://github.com/gql-dart/gql/pull/15), which will offer better support
